# Generated by Django 5.2.8 on 2026-04-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_usuarios_remove_contato_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='aniversario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='aniversario',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
